name: Ruby

on:
  push:
    branches:
      - main

  pull_request:

concurrency:
  group: ${{ github.head_ref || github.sha }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    name: ruby:${{ matrix.ruby }} fluentd:${{ matrix.fluentd}}
    strategy:
      fail-fast: false
      #matrix: ${{ fromJSON(needs.define-matrix.outputs.matrix) }}
      matrix:
        ruby:
          - '3.4'
          - '3.3'
          - '3.2'
          - '3.1'
          - '3.0'
          - '2.7'
        fluentd:
          - '1.19.0'
          - '1.16.10'
          - '1.0.2'
          - '0.12.43'
        exclude:
          - ruby: '3.1'
            fluentd: '1.19.0' # 1.19.0 requires Ruby >= 3.2
          - ruby: '3.0'
            fluentd: '1.19.0' # 1.19.0 requires Ruby >= 3.2
          - ruby: '2.7'
            fluentd: '1.19.0' # 1.19.0 requires Ruby >= 3.2
    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: false
      - name: Install dependency
        if: ${{ matrix.ruby }} == '2.7'
        run: |
          gem install fiber-storage -v 1.0.0
          gem install fiber-local -v 1.0.0
          gem install console -v 1.19.0
      - name: Install fluentd
        run: gem install fluentd -v ${{ matrix.fluentd }}
      - name: Install other gems
        run: bundle install
      - name: Run the default task
        run: bundle exec rake TESTOPTS='-v'
